version: 2

defaults: &defaults
  docker:
    - image: rdaniels6813/rust-bin:${CIRCLE_JOB}
  steps:
    - checkout
    - run:
        name: cargo build
        command: cargo build --release --target=${CIRCLE_JOB}
    - persist_to_workspace:
        root: /root/project/
        paths:
          - target/*/release/rust-hello-world*

jobs:
  # "armv7-unknown-linux-gnueabihf":
  #   <<: *defaults

  # "x86_64-apple-darwin":
  #   <<: *defaults

  # "x86_64-pc-windows-gnu":
  #   <<: *defaults

  # "x86_64-unknown-linux-gnu":
  #   <<: *defaults

  "x86_64-unknown-linux-musl":
    <<: *defaults

  deploy:
    docker:
      - image: rdaniels6813/semantic-release-alpine:latest
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /root/project
      - run:
          name: show contents
          command: ls -alhR target

workflows:
  version: 2
  build:
    jobs:
      # - "armv7-unknown-linux-gnueabihf"
      # - "x86_64-apple-darwin"
      # - "x86_64-pc-windows-gnu"
      # - "x86_64-unknown-linux-gnu"
      - "x86_64-unknown-linux-musl"
      - deploy
          requires:
            - "x86_64-unknown-linux-musl"
